import express from 'express';
import { errorHandler } from './middleware/errorHandler';
import { accountsRouter } from './routes/accounts';
import { activitiesRouter } from './routes/activities';
import { adminRouter } from './routes/admin';
import { announcementsRouter } from './routes/announcements';
import { authRouter } from './routes/auth';
import { cronRouter } from './routes/cron';
import { dashboardRouter } from './routes/dashboard';
import { filesRouter, projectFilesRouter } from './routes/files';
import { financeRouter } from './routes/finance';
import { invitesRouter } from './routes/invites';
import { materialsRouter } from './routes/materials';
import { meRouter } from './routes/me';
import { milestonesRouter } from './routes/milestones';
import { onsiteRouter } from './routes/onsite';
import { projectsRouter } from './routes/projects';
import { risksRouter } from './routes/risks';
import { stagesRouter } from './routes/stages';
import { todosRouter } from './routes/todos';
import { workModulesRouter } from './routes/workModules';
import { workSheetRouter } from './routes/workSheet';

export const app = express();
app.use(express.json({ limit: '2mb' }));

app.get('/api/health', (_req, res) => res.json({ ok: true }));

app.use('/api/auth', authRouter);
app.use('/api/admin', adminRouter);
app.use('/api/me', meRouter);
app.use('/api/projects', projectsRouter);
app.use('/api/invites', invitesRouter);
app.use('/api/projects/:id/files', projectFilesRouter);
app.use('/api/projects/:id/todos', todosRouter);
app.use('/api/projects/:id/work-modules', workModulesRouter);
app.use('/api/projects/:id/work-sheet', workSheetRouter);
app.use('/api/projects/:id/finance', financeRouter);
app.use('/api/projects/:id/materials', materialsRouter);
app.use('/api/projects/:id/accounts', accountsRouter);
app.use('/api/projects/:id/dashboard', dashboardRouter);
app.use('/api/projects/:id/onsite', onsiteRouter);
app.use('/api/projects/:id/risks', risksRouter);
app.use('/api/projects/:id/announcements', announcementsRouter);
app.use('/api/projects/:id/activities', activitiesRouter);
app.use('/api/projects/:id/stages', stagesRouter);
app.use('/api/projects/:id/milestones', milestonesRouter);
app.use('/api/files', filesRouter);
app.use('/api/cron', cronRouter);

app.use(errorHandler);
